theme: minima
title: minima
author:WilliamWilson8
email: 
description: > # this means to ignore newlines until "baseurl:"
  
# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  WilliamWilson8 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
